### ISSUE TITLE
half_min_plogp is frequently 0 when it shouldn't be

### ISSUE THREAD

**Issue by gridbugs** [math-fehr/fast-wfc#1]
`half_min_plogp` is used as an upper bound for the noise added to the entropy of a cell when choosing the min entropy cell to observe. A symptom of this problem is the noise applied to the entropy for certain source images being 0. I confirmed this by building and running `wfc` modified to print out `half_min_plogp`.

I think this is a symptom of a different problem - namely the function `get_plogp` gets passed frequencies of patterns (ie. the number of times each pattern appears in the source image), rather than the probabilities of patterns appearing in the source image. Notably, when the source image contains a pattern which appears exactly once, the value of `log([distribution[i])` is 0 for at least one `i` (since `log(1)=0`). Since `half_min_plogp` is based on the minimum value of the output of `get_plogp`, a 0 in its output results in `half_min_plogp` being 0.
https://github.com/math-fehr/fast-wfc/blob/ad73f8edc6c5e743b93d3d615efaafae8c4b2bc5/src/wave.hpp#L77

**Comment by math-fehr** [comment]
The frequency given was indeed not normalized, thanks for spotting that!

It should be fixed in f00f8af.
