### ISSUE TITLE
Using this implementation in other c++ code

### ISSUE THREAD

**Issue by ericoporto** [math-fehr/fast-wfc#4]
Hey, I would like to use this implementation in another cpp code. Are there plans to also make something like a libfastwfc with headers?

**Comment by math-fehr** [comment]
I guess I could do that, it would make things cleaner I guess.
I'll have some time this week-end to do it !

**Comment by ericoporto** [comment]
Awesome :) thanks for such amazing work.

**Comment by math-fehr** [comment]
I added CMake files to compile a fastwfc library, this works on my machine, though I'm not sure if it works on Windows/Mac !

**Comment by ericoporto** [comment]
Awesome. I am on Linux too. You can close this. :)
