### ISSUE TITLE
FASTWFC_LIB used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by ericoporto** [math-fehr/fast-wfc#5]
Hey, I am trying to build but I am getting this error:

```
~/git$ cd fast-wfc/
~/git/fast-wfc$ cmake .
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FASTWFC_LIB
    linked by target "wfc_demo" in directory /home/username/git/fast-wfc/example

-- Configuring incomplete, errors occurred!
See also "/home/username/git/fast-wfc/CMakeFiles/CMakeOutput.log".
```

It seems that the `CMakeLists.txt` from examples, require the library already built and installed.

```
find_library( FASTWFC_LIB
  NAMES
    fastwfc_static
  HINTS
    /usr/local/lib64
    )
```

But the `CMakeLists.txt` for the library, require the examples to be built! 

```
add_subdirectory(example)
```

I had to comment the above line from the library (last line from `CMakeLists.txt`), build it, before building examples.

**Comment by math-fehr** [comment]
Oh yeah, sorry for the mistake !
It's now fixed in 0e7657a.

**Comment by ericoporto** [comment]
just a question, are the examples producing the image output for you? For me I get success messages on the terminal but no results directory is getting created. If you can reproduce I would open an issue. Also, a differente issue, but cmake, for the examples, fail on Windows without being able to generate an output, I imagine the find library is the thing failing there.

**Comment by math-fehr** [comment]
I just fixed the results issues!
On windows the problem might come from
```
find_library( FASTWFC_LIB
  NAMES
    fastwfc_static
  HINTS
    /usr/local/lib64
    )
```
in the CMakeLists in example. HINTS is here the place where the library is installed on Linux, but I haven't specified where to look for Windows. If you replace or add the correct path after HINTS it should work (I don't know where the library is installed on Windows, but it should be written somewhere when you install the library).
