### ISSUE TITLE
Build Warnings in x64

### ISSUE THREAD

**Issue by bleachkitty** [math-fehr/fast-wfc#7]
I'm getting several build warning in x64 on Visual Studio 2019 related to size mismatches.  This happens when size_t's are being implicitly converted to 32-bit types, like int.  Here's the full output:

1>------ Build started: Project: FastWFC, Configuration: Release x64 ------
1>propagator.cpp
1>C:\bob\proj\dev\dl\3rdParty\FastWFC\src\include\propagator.hpp(72,1): warning C4267: 'initializing': conversion from 'size_t' to 'const unsigned int', possible loss of data
1>wave.cpp
1>C:\bob\proj\dev\dl\3rdParty\FastWFC\src\lib\propagator.cpp(13,20): warning C4267: '=': conversion from 'size_t' to '_Ty', possible loss of data
1>C:\bob\proj\dev\dl\3rdParty\FastWFC\src\lib\propagator.cpp(13,20): warning C4267:         with
1>C:\bob\proj\dev\dl\3rdParty\FastWFC\src\lib\propagator.cpp(13,20): warning C4267:         [
1>C:\bob\proj\dev\dl\3rdParty\FastWFC\src\lib\propagator.cpp(13,20): warning C4267:             _Ty=int
1>C:\bob\proj\dev\dl\3rdParty\FastWFC\src\lib\propagator.cpp(13,20): warning C4267:         ]
1>C:\bob\proj\dev\dl\3rdParty\FastWFC\src\lib\wave.cpp(39,26): warning C4267: 'initializing': conversion from 'size_t' to 'const unsigned int', possible loss of data
1>C:\bob\proj\dev\dl\3rdParty\FastWFC\src\lib\wave.cpp(96,26): warning C4458: declaration of 'nb_patterns' hides class member
1>wfc.cpp
1>C:\bob\proj\dev\dl\3rdParty\FastWFC\src\include\wave.hpp(58,18): message : see declaration of 'Wave::nb_patterns'
1>C:\bob\proj\dev\dl\3rdParty\FastWFC\src\include\propagator.hpp(72,1): warning C4267: 'initializing': conversion from 'size_t' to 'const unsigned int', possible loss of data
1>C:\bob\proj\dev\dl\3rdParty\FastWFC\src\lib\wfc.cpp(44,70): warning C4267: 'initializing': conversion from 'size_t' to 'const unsigned int', possible loss of data
1>FastWFC.vcxproj -> C:\bob\proj\dev\dl\3rdParty\FastWFC\bin\Release\x64\FastWFC.lib
1>Done building project "FastWFC.vcxproj".

**Comment by math-fehr** [comment]
Hey, thanks for letting me know.
I'll correct that this week when I have some time!

**Comment by math-fehr** [comment]
Sorry for the delay.
This should be fixed now with the last commits!
